# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=30)),
                ('course_code', models.CharField(max_length=10)),
                ('logo', models.ImageField(upload_to='static/courses')),
                ('homepage', models.URLField()),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='LinkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('thumbnail', models.ImageField(upload_to='static/link_categories')),
            ],
            options={
                'verbose_name_plural': 'link categories',
            },
        ),
        migrations.CreateModel(
            name='MainProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Felles', max_length=40)),
                ('nickname', models.CharField(default='Felles', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'main profiles',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('main_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='semesterpage.MainProfile')),
            ],
            options={
                'ordering': ['study_program', 'number'],
            },
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('full_name', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('program_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='semester',
            name='study_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='semesterpage.StudyProgram'),
        ),
        migrations.AddField(
            model_name='mainprofile',
            name='study_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainProfiles', to='semesterpage.StudyProgram'),
        ),
        migrations.AddField(
            model_name='link',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semesterpage.LinkCategory'),
        ),
        migrations.AddField(
            model_name='link',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semesterpage.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='semesters',
            field=models.ManyToManyField(related_name='courses', to='semesterpage.Semester'),
        ),
    ]
