# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='')),
                ('homepage', models.URLField()),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='LinkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('full_name', models.CharField(max_length=30)),
                ('abbreviation', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='semester',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semesterpage.Study'),
        ),
        migrations.AddField(
            model_name='link',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semesterpage.LinkCategory'),
        ),
        migrations.AddField(
            model_name='link',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semesterpage.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='semesters',
            field=models.ManyToManyField(to='semesterpage.Semester'),
        ),
    ]
