# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='semesterpage.Course'),
        ),
    ]
