# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselink',
            name='custom_category',
            field=models.ForeignKey(blank=True, default=None, help_text='Hvis du ønsker å bruke et egendefinert "mini-ikon".', null=True, on_delete=django.db.models.deletion.SET_NULL, to='semesterpage.CustomLinkCategory', verbose_name='(Egendefinert kategori)'),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='custom_category',
            field=models.ForeignKey(blank=True, default=None, help_text='Hvis du ønsker å bruke et egendefinert "mini-ikon".', null=True, on_delete=django.db.models.deletion.SET_NULL, to='semesterpage.CustomLinkCategory', verbose_name='(Egendefinert kategori)'),
        ),
    ]
