# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0002_auto_20160616_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.ImageField(upload_to='semesterpage/static/semesterpage/course_logos'),
        ),
        migrations.AlterField(
            model_name='linkcategory',
            name='thumbnail',
            field=models.ImageField(upload_to='semesterpage/static/semesterpage/link_category_logos'),
        ),
    ]
