# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0003_load_init_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Hvem som opprettet faget.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to='semesterpage.Contributor'),
        ),
    ]
