# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0003_auto_20160616_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='nickname',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='mainprofile',
            old_name='nickname',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='studyprogram',
            old_name='nickname',
            new_name='display_name',
        ),
    ]
