# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import semesterpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0004_course_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='resourcelinklist',
            name='logo',
        ),
        migrations.AddField(
            model_name='course',
            name='safe_logo',
            field=models.ImageField(blank=True, help_text='Bildet vises over alle lenkene knyttet til faget. NB! Bildet skaleres automatisk til å bli kvadratisk.', null=True, upload_to=semesterpage.models.upload_path, verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='course',
            name='unsafe_logo',
            field=models.FileField(blank=True, null=True, upload_to=semesterpage.models.upload_path),
        ),
        migrations.AddField(
            model_name='resourcelinklist',
            name='safe_logo',
            field=models.ImageField(blank=True, help_text='Bildet vises over alle lenkene knyttet til faget. NB! Bildet skaleres automatisk til å bli kvadratisk.', null=True, upload_to=semesterpage.models.upload_path, verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='resourcelinklist',
            name='unsafe_logo',
            field=models.FileField(blank=True, null=True, upload_to=semesterpage.models.upload_path),
        ),
    ]
