# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0004_auto_20160617_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='linkcategory',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.ImageField(upload_to='semesterpage/static/semesterpage/courses'),
        ),
        migrations.AlterField(
            model_name='linkcategory',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='linkcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='semesterpage/static/semesterpage/link_categories'),
        ),
    ]
