# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0005_auto_20160618_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(help_text='F.eks. "TDT4102"', max_length=10, primary_key=True, serialize=False, verbose_name='emnekode'),
        ),
        migrations.AlterField(
            model_name='course',
            name='display_name',
            field=models.CharField(help_text='F.eks. "C++"', max_length=30, verbose_name='visningsnavn'),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_name',
            field=models.CharField(help_text='F.eks. "Prosedyre- og Objektorientert Programmering"', max_length=50, unique=True, verbose_name='fullt navn'),
        ),
        migrations.AlterField(
            model_name='course',
            name='homepage',
            field=models.URLField(help_text='F.eks. "http://home.phys.ntnu.no/fysikkfag/eksamensoppgaver"', verbose_name='Fagets hjemmeside'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(help_text='F.eks "Gamle eksamenssett"', max_length=30, verbose_name='tittel'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(help_text='F.eks. "http://www.phys.ntnu.no/fysikkfag/gamleeksamener.html"', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='linkcategory',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='kategorinavn'),
        ),
        migrations.AlterField(
            model_name='linkcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='semesterpage/static/semesterpage/link_categories', verbose_name='ikon for kategori'),
        ),
        migrations.AlterField(
            model_name='mainprofile',
            name='display_name',
            field=models.CharField(default='Felles', help_text='F.eks. "InMat"', max_length=30, verbose_name='visningsnavn / kallenavn'),
        ),
        migrations.AlterField(
            model_name='mainprofile',
            name='full_name',
            field=models.CharField(default='felles', help_text='F.eks. "Industriell matematikk"', max_length=40, verbose_name='fullt navn'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.PositiveSmallIntegerField(help_text='F.eks. "2"', verbose_name='semester (nummer)'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='display_name',
            field=models.CharField(help_text='F.eks. "Fysmat"', max_length=30, verbose_name='visningsnavn / kallenavn'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='full_name',
            field=models.CharField(help_text='F.eks. "Fysikk og matematikk"', max_length=30, verbose_name='fullt navn'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='program_code',
            field=models.CharField(help_text='F.eks. "MTFYMA"', max_length=10, primary_key=True, serialize=False, verbose_name='programkode'),
        ),
    ]
