# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0006_auto_20160619_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='display_name',
            field=models.CharField(help_text='F.eks. "C++"', max_length=60, verbose_name='visningsnavn'),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_name',
            field=models.CharField(help_text='F.eks. "Prosedyre- og Objektorientert Programmering"', max_length=60, unique=True, verbose_name='fullt navn'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(help_text='F.eks "Gamle eksamenssett"', max_length=60, verbose_name='tittel'),
        ),
        migrations.AlterField(
            model_name='linkcategory',
            name='name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='kategorinavn'),
        ),
        migrations.AlterField(
            model_name='mainprofile',
            name='display_name',
            field=models.CharField(default='Felles', help_text='F.eks. "InMat"', max_length=60, verbose_name='visningsnavn / kallenavn'),
        ),
        migrations.AlterField(
            model_name='mainprofile',
            name='full_name',
            field=models.CharField(default='felles', help_text='F.eks. "Industriell matematikk"', max_length=60, verbose_name='fullt navn'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='display_name',
            field=models.CharField(help_text='F.eks. "Fysmat"', max_length=60, verbose_name='visningsnavn / kallenavn'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='full_name',
            field=models.CharField(help_text='F.eks. "Fysikk og matematikk"', max_length=60, verbose_name='fullt navn'),
        ),
    ]
