# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0007_auto_20160807_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='homepage',
            field=models.CharField(blank=True, help_text='Fagene du velger nedenfor vil dukke opp på hjemmesiden din. Du kan besøke din personlige semesterside på kokekunster.no/hjemmesidenavn.', max_length=60, null=True, unique=True, verbose_name='hjemmesidenavn'),
        ),
    ]
