# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import semesterpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0007_auto_20160620_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['full_name'], 'verbose_name': 'fag', 'verbose_name_plural': 'fag'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'lenke', 'verbose_name_plural': 'lenker'},
        ),
        migrations.AlterModelOptions(
            name='linkcategory',
            options={'verbose_name': 'lenkekategori', 'verbose_name_plural': 'lenkekategorier'},
        ),
        migrations.AlterModelOptions(
            name='mainprofile',
            options={'ordering': ['full_name'], 'verbose_name': 'hovedprofil', 'verbose_name_plural': 'hovedprofiler'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['study_program', 'number'], 'verbose_name': 'semester', 'verbose_name_plural': 'semestere'},
        ),
        migrations.AlterModelOptions(
            name='studyprogram',
            options={'ordering': ['full_name'], 'verbose_name': 'studieprogram', 'verbose_name_plural': 'studieprogram'},
        ),
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.ImageField(upload_to=semesterpage.models.upload_path),
        ),
    ]
