# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0008_auto_20160622_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='semesterpage.LinkCategory'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='main_profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semesters', to='semesterpage.MainProfile'),
        ),
    ]
