# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 22:20
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0008_auto_20160812_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='display_name', unique_with=('study_program',)),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='display_name', unique=True),
        ),
    ]
