# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0009_auto_20160813_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(db_index=True, help_text='F.eks. "TDT4102"', max_length=10, unique=True, verbose_name='emnekode'),
        ),
    ]
