# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0009_auto_20160622_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('order',), 'verbose_name': 'lenke', 'verbose_name_plural': 'lenker'},
        ),
        migrations.AddField(
            model_name='link',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
