# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0010_auto_20160622_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order'], 'verbose_name': 'fag', 'verbose_name_plural': 'fag'},
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
