# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0010_auto_20170801_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='display_name',
            field=models.CharField(blank=True, help_text='F.eks. "C++"', max_length=60, verbose_name='visningsnavn'),
        ),
        migrations.AlterField(
            model_name='resourcelinklist',
            name='display_name',
            field=models.CharField(blank=True, help_text='F.eks. "C++"', max_length=60, verbose_name='visningsnavn'),
        ),
    ]
