# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0011_auto_20170801_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='full_name',
            field=models.CharField(help_text='F.eks. "Prosedyre- og Objektorientert Programmering"', max_length=120, unique=True, verbose_name='fullt navn'),
        ),
        migrations.AlterField(
            model_name='resourcelinklist',
            name='full_name',
            field=models.CharField(help_text='F.eks. "Prosedyre- og Objektorientert Programmering"', max_length=120, unique=True, verbose_name='fullt navn'),
        ),
    ]
