# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0011_auto_20160622_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['full_name'], 'verbose_name': 'fag', 'verbose_name_plural': 'fag'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='order',
        ),
    ]
