# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0012_auto_20170801_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='homepage',
            field=models.URLField(blank=True, help_text='F.eks. "http://www.phys.ntnu.no/fysikkfag/". Denne lenken kan besøkes ved å trykke på ikonet til faget.', verbose_name='Fagets hjemmeside'),
        ),
        migrations.AlterField(
            model_name='resourcelinklist',
            name='homepage',
            field=models.URLField(blank=True, help_text='F.eks. "http://www.phys.ntnu.no/fysikkfag/". Denne lenken kan besøkes ved å trykke på ikonet til faget.', verbose_name='Fagets hjemmeside'),
        ),
    ]
