# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 10:53
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0013_auto_20170801_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='homepage',
        ),
        migrations.AlterField(
            model_name='options',
            name='homepage_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='user.username', unique=True),
        ),
    ]
