# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0014_auto_20170802_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='homepage_slug',
        ),
    ]
