# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0015_remove_options_homepage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='self_chosen_semester',
            field=models.ForeignKey(blank=True, default=None, help_text='Alle fagene til dette semesteret vil dukke opp på hjemmesiden din, i tillegg til de fagene du er opmeldt i.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='semesterpage.Semester', verbose_name='semester'),
        ),
    ]
