# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0016_auto_20170802_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dataporten_uid',
            field=models.CharField(help_text='Dataporten unik id', max_length=60, null=True, unique=True, verbose_name='dataporten uid'),
        ),
        migrations.AddField(
            model_name='options',
            name='active_dataporten_courses',
            field=models.ManyToManyField(blank=True, default=None, help_text='Aktive fag fra dataporten', null=True, related_name='active_students', to='semesterpage.Course', verbose_name='dataporten fag'),
        ),
        migrations.AlterField(
            model_name='options',
            name='self_chosen_courses',
            field=models.ManyToManyField(blank=True, default=None, help_text='Dette er fagene som vises på profilsiden din.', related_name='students', to='semesterpage.Course', verbose_name='fag'),
        ),
        migrations.AlterField(
            model_name='options',
            name='self_chosen_semester',
            field=models.ForeignKey(blank=True, default=None, help_text='Alle fagene til dette semesteret vil dukke opp på hjemmesiden din, i tillegg til de fagene du har valgt nedenfor.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='semesterpage.Semester', verbose_name='semester'),
        ),
    ]
