# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0018_auto_20170806_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='semester',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributors', to='semesterpage.Semester', verbose_name='bidragsytersemester'),
        ),
        migrations.AlterField(
            model_name='options',
            name='self_chosen_semester',
            field=models.ForeignKey(blank=True, default=None, help_text='Alle fagene til dette semesteret vil dukke opp på hjemmesiden din, i tillegg til de fagene du har valgt nedenfor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='semesterpage.Semester', verbose_name='semester'),
        ),
    ]
