# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0020_auto_20170806_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='self_chosen_semester',
        ),
    ]
