# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0021_remove_options_self_chosen_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='has_electives',
            field=models.BooleanField(default=False, help_text='Huk av hvis dette semesteret har valgfag. I så fall vises et ekstra generisk "valgfag" på nettsiden til semesteret, hvor brukeren bes om å logge på for å velge valgfagene.', verbose_name='valgfag'),
        ),
    ]
