# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 21:27
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import semesterpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0022_semester_has_electives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=semesterpage.models.norwegian_slugify, unique_with=('study_program',)),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=semesterpage.models.norwegian_slugify, unique=True),
        ),
    ]
