# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import semesterpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0024_course_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='safe_logo',
            field=models.ImageField(blank=True, help_text='Bildet vises over alle lenkene knyttet til faget. NB! Bildet skaleres automatisk til å bli kvadratisk, .svg bilder er ikke støttet.', null=True, upload_to=semesterpage.models.upload_path, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='resourcelinklist',
            name='safe_logo',
            field=models.ImageField(blank=True, help_text='Bildet vises over alle lenkene knyttet til faget. NB! Bildet skaleres automatisk til å bli kvadratisk, .svg bilder er ikke støttet.', null=True, upload_to=semesterpage.models.upload_path, verbose_name='logo'),
        ),
    ]
