# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0026_auto_20170815_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='last_user_modification',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='sist redigert'),
        ),
    ]
