# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0027_options_last_user_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='published',
            field=models.BooleanField(default=False, help_text='Semesteret dukker ikke opp i navigasjonsbaren før det er publisert, men det er fortsatt mulig å besøke semesteret manuelt (URL: wikilinks.no/studieprogram/hovedprofil/semesternummer) for å teste resultatet før du publiserer.', verbose_name='publisert'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='has_archive',
            field=models.BooleanField(default=False, help_text='Huk av hvis studieprogrammet har filer i arkivet på wikilinks.no/arkiv.', verbose_name='har arkiv'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='published',
            field=models.BooleanField(default=False, help_text='Studieprogrammet dukker ikke opp i studieprogramlisten i navigasjonsbaren før det er publisert, men det er fortsatt mulig å besøke studieprogrammet manuelt (URL: wikilinks.no/visningsnavn) for å teste resultatet før du publiserer.', verbose_name='publisert'),
        ),
    ]
