# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-27 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0028_auto_20170906_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(db_index=True, help_text='F.eks. "TDT4102"', max_length=15, unique=True, verbose_name='emnekode'),
        ),
    ]
