# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-09 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examurl',
            name='language',
            field=models.CharField(choices=[('Bokmål', 'Bokmål'), ('Nynorsk', 'Nynorsk'), ('Engelsk', 'Engelsk'), (None, 'Ukjent')], help_text='Språket som eksamen er skrevet i.', max_length=20, null=True),
        ),
    ]
