# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-09 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebackup',
            name='filetype',
            field=models.CharField(default='pdf', help_text='Filendelsetype.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='filebackup',
            name='string_content',
            field=models.TextField(default=None, help_text='Filinnhold i rent tekstformat.', null=True),
        ),
    ]
