# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-25 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentinfo',
            name='season',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Vår'), (2, 'Kont'), (3, 'Høst'), (None, 'Ukjent')], help_text='Semestertype når eksamen ble holdt.', null=True),
        ),
    ]
