# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-09 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0001_squashed_0003_auto_20181209_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebackup',
            name='filetype',
            field=models.CharField(default='pdf', help_text='Filendelsestype, f.eks. "pdf".', max_length=10, null=True),
        ),
    ]
