# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-11 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0002_auto_20181209_2227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileBackup',
            new_name='ScrapedPdf',
        ),
        migrations.AlterField(
            model_name='examurl',
            name='verified_by',
            field=models.ManyToManyField(help_text='Brukere som har verifisert metadataen.', to=settings.AUTH_USER_MODEL),
        ),
    ]
