# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-09 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0002_auto_20181209_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filebackup',
            old_name='string_content',
            new_name='text',
        ),
    ]
