# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-11 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0003_auto_20181211_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examurl',
            old_name='file_backup',
            new_name='scraped_pdf',
        ),
    ]
