# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-11 19:19
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0028_auto_20170906_2226'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examiner', '0004_auto_20181211_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedPdfUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True, validators=[django.core.validators.URLValidator()])),
                ('filename', models.CharField(help_text='Ressursens filnavn.', max_length=255)),
                ('course_code', models.CharField(blank=True, help_text='Eksamens fagkode.', max_length=10, null=True)),
                ('language', models.CharField(choices=[('Bokmål', 'Bokmål'), ('Nynorsk', 'Nynorsk'), ('Engelsk', 'Engelsk'), (None, 'Ukjent')], help_text='Språket som eksamen er skrevet i.', max_length=20, null=True)),
                ('year', models.PositiveSmallIntegerField(help_text='Året som eksamen ble holdt.', null=True)),
                ('season', models.PositiveSmallIntegerField(choices=[(1, 'Vår'), (2, 'Kontinuasjonseksamen'), (3, 'Høst'), (None, 'Ukjent')], help_text='Semestertype når eksamen ble holdt.', null=True)),
                ('solutions', models.BooleanField(default=False, help_text='Om filen inneholder løsningsforslag.')),
                ('probably_exam', models.BooleanField(default=False, help_text='Om denne filen trolig er relatert til en eksamen.')),
                ('dead_link', models.NullBooleanField(default=None, help_text='Om URLen faktisk tjener relevant innhold.')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('course', models.ForeignKey(blank=True, help_text='Faget som eksamenen tilhører.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_urls', to='semesterpage.Course')),
                ('scraped_pdf', models.ForeignKey(help_text='Kopi av filen fra URLen.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_at', to='examiner.ScrapedPdf')),
                ('verified_by', models.ManyToManyField(help_text='Brukere som har verifisert metadataen.', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='examurl',
            name='course',
        ),
        migrations.RemoveField(
            model_name='examurl',
            name='scraped_pdf',
        ),
        migrations.RemoveField(
            model_name='examurl',
            name='verified_by',
        ),
        migrations.DeleteModel(
            name='ExamURL',
        ),
    ]
