# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-11 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0005_auto_20181211_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedpdf',
            name='filetype',
        ),
    ]
