# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-20 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0008_auto_20181215_2306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapedPdf',
            new_name='Pdf',
        ),
    ]
