# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-23 19:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0010_auto_20181220_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Sidetall.')),
                ('text', models.TextField(help_text='Sideinnhold i rent tekstformat.')),
                ('confidence', models.PositiveIntegerField(default=None, help_text='Konfidens til evt. OCR av tekstinnhold.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pdf', models.ForeignKey(help_text='Tilhørende PDF fil.', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='examiner.Pdf')),
            ],
            options={
                'ordering': ('pdf', 'number'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='pdfpage',
            unique_together=set([('pdf', 'number')]),
        ),
    ]
