# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-23 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0011_auto_20181223_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='text',
        ),
    ]
