# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-23 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0028_auto_20170906_2226'),
        ('examiner', '0012_remove_pdf_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, help_text='Eksamens fagkode.', max_length=10, null=True)),
                ('language', models.CharField(choices=[('Bokmål', 'Bokmål'), ('Nynorsk', 'Nynorsk'), ('Engelsk', 'Engelsk'), (None, 'Ukjent')], help_text='Språket som eksamen er skrevet i.', max_length=20, null=True)),
                ('year', models.PositiveSmallIntegerField(help_text='Året som eksamen ble holdt.', null=True)),
                ('season', models.PositiveSmallIntegerField(choices=[(1, 'Vår'), (2, 'Kontinuasjonseksamen'), (3, 'Høst'), (None, 'Ukjent')], help_text='Semestertype når eksamen ble holdt.', null=True)),
                ('solutions', models.BooleanField(default=False, help_text='Om filen inneholder løsningsforslag.')),
                ('course', models.ForeignKey(blank=True, help_text='Faget som eksamenen tilhører.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_urls', to='semesterpage.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='pdfurl',
            name='course',
        ),
        migrations.RemoveField(
            model_name='pdfurl',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='pdfurl',
            name='language',
        ),
        migrations.RemoveField(
            model_name='pdfurl',
            name='season',
        ),
        migrations.RemoveField(
            model_name='pdfurl',
            name='solutions',
        ),
        migrations.RemoveField(
            model_name='pdfurl',
            name='year',
        ),
        migrations.AddField(
            model_name='pdfurl',
            name='exam',
            field=models.ForeignKey(default=1, help_text='Hvilket eksamenssett URLen trolig tjener.', on_delete=django.db.models.deletion.CASCADE, to='examiner.Exam'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set([('course_code', 'language', 'year', 'season', 'solutions')]),
        ),
    ]
