# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-24 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0013_auto_20181223_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfurl',
            name='exam',
            field=models.ForeignKey(help_text='Hvilket eksamenssett URLen trolig tjener.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='examiner.Exam'),
        ),
    ]
