# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-26 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0016_auto_20181226_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='content_type',
            field=models.CharField(choices=[('Exam', 'Eksamen'), ('Exercise', 'Øving'), ('Other', 'Annet'), (None, 'Ubestemt')], default=None, help_text='PDF-ens innholdstype, f.eks. "eksamen".', max_length=20, null=True),
        ),
    ]
