# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-30 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesterpage', '0029_auto_20181228_0012'),
        ('examiner', '0018_auto_20181229_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRelatedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_course_code', models.CharField(help_text='Emnekoden til sekundærfaget, f.eks. "SIF5013".', max_length=15, unique=True, verbose_name='sekundæremnekode')),
                ('primary_course', models.ForeignKey(help_text='Faget som regnes som hovedfaget.', on_delete=django.db.models.deletion.CASCADE, related_name='secondary_courses', to='semesterpage.Course')),
                ('secondary_course', models.OneToOneField(blank=True, help_text='Faget som er underordnet hovedfaget.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_course', to='semesterpage.Course')),
            ],
        ),
    ]
