# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-30 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examiner', '0019_examrelatedcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examiner.Exam')),
            ],
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='exam',
        ),
        migrations.AddField(
            model_name='exampdf',
            name='pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examiner.Pdf'),
        ),
        migrations.AddField(
            model_name='exampdf',
            name='verified_by',
            field=models.ManyToManyField(help_text='Brukere som har verifisert metadataen.', related_name='verified_exam_pdfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pdf',
            name='exams',
            field=models.ManyToManyField(help_text='Hvilke eksamenssett PDFen trolig inneholder.', null=True, related_name='pdfs', through='examiner.ExamPdf', to='examiner.Exam'),
        ),
    ]
