# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-01 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0020_auto_20181230_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exam',
            new_name='DocumentInfo',
        ),
    ]
