# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-01 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0021_auto_20190101_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinfo',
            name='content_type',
            field=models.CharField(blank=True, choices=[('Exam', 'Eksamen'), ('Exercise', 'Øving'), ('Project', 'Prosjekt'), ('Irrelevant', 'Urelevant'), (None, 'Ubestemt')], default=None, help_text='PDF-ens innholdstype, f.eks. "eksamen".', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentinfo',
            name='exercise_number',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Øvingsnummer hvis dokumentet er en øving eller et prosjekt.', null=True, verbose_name='Øvingsnummer'),
        ),
        migrations.AlterField(
            model_name='documentinfo',
            name='language',
            field=models.CharField(blank=True, choices=[('Bokmål', 'Bokmål'), ('Nynorsk', 'Nynorsk'), ('Engelsk', 'Engelsk'), (None, 'Ukjent')], help_text='Språket som eksamen er skrevet i.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documentinfo',
            name='season',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Vår'), (2, 'Kontinuasjonseksamen'), (3, 'Høst'), (None, 'Ukjent')], help_text='Semestertype når eksamen ble holdt.', null=True),
        ),
        migrations.AlterField(
            model_name='documentinfo',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Året som eksamen ble holdt.', null=True),
        ),
        migrations.AlterField(
            model_name='pdfurl',
            name='exam',
            field=models.ForeignKey(help_text='Hvilken innholdstype URLen trolig tjener.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='examiner.DocumentInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='documentinfo',
            unique_together=set([('content_type', 'course_code', 'language', 'year', 'season', 'solutions', 'exercise_number')]),
        ),
    ]
