# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-01 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0022_auto_20190101_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='documentinfo',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Faget som eksamenen tilhører.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docinfos', to='semesterpage.Course'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='exams',
            field=models.ManyToManyField(help_text='Hvilke eksamenssett PDFen trolig inneholder.', related_name='pdfs', through='examiner.ExamPdf', to='examiner.DocumentInfo'),
        ),
        migrations.AlterField(
            model_name='pdfurl',
            name='exam',
            field=models.ForeignKey(help_text='Hvilken innholdstype URLen trolig tjener.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls', to='examiner.DocumentInfo'),
        ),
    ]
