# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-01 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0023_auto_20190101_2137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamPdf',
            new_name='DocumentInfoSource',
        ),
        migrations.RenameField(
            model_name='documentinfosource',
            old_name='exam',
            new_name='document_info',
        ),
    ]
